/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiConfigDialog: typeof import('./components/dialogs/AiConfigDialog.vue')['default']
    AnalysisEvidencePanel: typeof import('./components/analysis/AnalysisEvidencePanel.vue')['default']
    AnalysisTaskProgress: typeof import('./components/analysis/AnalysisTaskProgress.vue')['default']
    CreateWorkspaceDialog: typeof import('./components/workspace/CreateWorkspaceDialog.vue')['default']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    InspectionLogsDialog: typeof import('./components/dialogs/InspectionLogsDialog.vue')['default']
    MemberManagement: typeof import('./components/members/MemberManagement.vue')['default']
    ProjectDialog: typeof import('./components/dialogs/ProjectDialog.vue')['default']
    RegressionPlanPanel: typeof import('./components/analysis/RegressionPlanPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorkspaceSwitcher: typeof import('./components/workspace/WorkspaceSwitcher.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
