-- 为 Impact Flow 现有表和字段补充中文注释
-- 适用于 MySQL 8.0+

USE impact_flow;

ALTER TABLE project COMMENT = '服务配置表';

ALTER TABLE project
  MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '服务主键ID（UUID）',
  MODIFY COLUMN name VARCHAR(100) NOT NULL COMMENT '服务名称',
  MODIFY COLUMN code VARCHAR(100) NOT NULL COMMENT '服务唯一编码',
  MODIFY COLUMN repository_url VARCHAR(1000) NOT NULL COMMENT 'Codeup Git仓库地址',
  MODIFY COLUMN production_branch VARCHAR(200) NOT NULL DEFAULT 'production' COMMENT '生产发布分支',
  MODIFY COLUMN last_analyzed_commit VARCHAR(64) NULL COMMENT '最近一次成功检测的目标提交SHA',
  MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
    ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

ALTER TABLE `release` COMMENT = '发布版本记录表';

ALTER TABLE `release`
  MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '发布记录主键ID（UUID）',
  MODIFY COLUMN project_id CHAR(36) NOT NULL COMMENT '关联服务ID',
  MODIFY COLUMN base_commit VARCHAR(64) NOT NULL COMMENT '上一检测版本提交SHA',
  MODIFY COLUMN target_commit VARCHAR(64) NOT NULL COMMENT '当前生产版本提交SHA',
  MODIFY COLUMN version VARCHAR(100) NULL COMMENT '业务发布版本号',
  MODIFY COLUMN status VARCHAR(30) NOT NULL COMMENT '发布检测状态',
  MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';

ALTER TABLE analysis_task COMMENT = '变更影响分析任务表';

ALTER TABLE analysis_task
  MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '分析任务主键ID（UUID）',
  MODIFY COLUMN project_id CHAR(36) NOT NULL COMMENT '关联服务ID',
  MODIFY COLUMN release_id CHAR(36) NOT NULL COMMENT '关联发布记录ID',
  MODIFY COLUMN base_commit VARCHAR(64) NOT NULL COMMENT '分析起始提交SHA',
  MODIFY COLUMN target_commit VARCHAR(64) NOT NULL COMMENT '分析目标提交SHA',
  MODIFY COLUMN status VARCHAR(30) NOT NULL COMMENT '任务状态：READY/RUNNING/SUCCESS/FAILED/NO_CHANGES',
  MODIFY COLUMN commit_count INT NOT NULL DEFAULT 0 COMMENT '间隔提交数量',
  MODIFY COLUMN changed_file_count INT NOT NULL DEFAULT 0 COMMENT '变更文件数量',
  MODIFY COLUMN additions INT NOT NULL DEFAULT 0 COMMENT '新增代码行数',
  MODIFY COLUMN deletions INT NOT NULL DEFAULT 0 COMMENT '删除代码行数',
  MODIFY COLUMN commit_summary JSON NULL COMMENT '提交摘要列表（JSON）',
  MODIFY COLUMN error_message VARCHAR(2000) NULL COMMENT '分析失败错误信息',
  MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '任务创建时间',
  MODIFY COLUMN finished_at DATETIME(3) NULL COMMENT '任务完成时间';

ALTER TABLE change_file COMMENT = '分析任务变更文件明细表';

ALTER TABLE change_file
  MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '变更文件主键ID（UUID）',
  MODIFY COLUMN analysis_task_id CHAR(36) NOT NULL COMMENT '关联分析任务ID',
  MODIFY COLUMN file_path VARCHAR(1000) NOT NULL COMMENT '变更后的文件路径',
  MODIFY COLUMN old_path VARCHAR(1000) NULL COMMENT '重命名前的文件路径',
  MODIFY COLUMN change_type VARCHAR(10) NOT NULL COMMENT '变更类型：A新增/M修改/D删除/R重命名/C复制/T类型变化/U未合并',
  MODIFY COLUMN additions INT NOT NULL DEFAULT 0 COMMENT '文件新增行数',
  MODIFY COLUMN deletions INT NOT NULL DEFAULT 0 COMMENT '文件删除行数',
  MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';

