-- 为当前全部业务表和字段补齐中文注释
-- 适用于 MySQL 8.0+

USE impact_flow;

ALTER TABLE project COMMENT = '服务配置表';
ALTER TABLE project
  MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '服务主键ID（UUID）',
  MODIFY COLUMN name VARCHAR(100) NOT NULL COMMENT '服务名称',
  MODIFY COLUMN code VARCHAR(100) NOT NULL COMMENT '服务唯一编码',
  MODIFY COLUMN repository_url VARCHAR(1000) NOT NULL COMMENT 'Git仓库地址',
  MODIFY COLUMN production_branch VARCHAR(200) NOT NULL DEFAULT 'production' COMMENT '待巡检的目标分支',
  MODIFY COLUMN last_analyzed_commit VARCHAR(64) NULL COMMENT '最近一次完成变更分析的提交SHA',
  MODIFY COLUMN detected_commit VARCHAR(64) NULL COMMENT '最近一次巡检发现的提交SHA',
  MODIFY COLUMN previous_detected_commit VARCHAR(64) NULL COMMENT '上一次巡检发现的提交SHA',
  MODIFY COLUMN pending_commit_count INT NOT NULL DEFAULT 0 COMMENT '当前待检测提交数量',
  MODIFY COLUMN pending_commits JSON NULL COMMENT '当前待检测提交摘要列表（JSON）',
  MODIFY COLUMN last_checked_at DATETIME(3) NULL COMMENT '最近一次巡检时间',
  MODIFY COLUMN check_status VARCHAR(20) NOT NULL DEFAULT 'IDLE' COMMENT '巡检状态：IDLE/CHECKING/SUCCESS/FAILED',
  MODIFY COLUMN check_error VARCHAR(2000) NULL COMMENT '最近一次巡检失败信息',
  MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
    ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

ALTER TABLE project_inspection_log COMMENT = '服务巡检日志表';
ALTER TABLE project_inspection_log
  MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '巡检日志主键ID（UUID）',
  MODIFY COLUMN project_id CHAR(36) NOT NULL COMMENT '关联服务ID',
  MODIFY COLUMN trigger_type VARCHAR(20) NOT NULL COMMENT '触发方式：MANUAL/SCHEDULED',
  MODIFY COLUMN status VARCHAR(20) NOT NULL COMMENT '巡检状态：RUNNING/SUCCESS/FAILED',
  MODIFY COLUMN detected_commit VARCHAR(64) NULL COMMENT '本次巡检发现的提交SHA',
  MODIFY COLUMN pending_commit_count INT NOT NULL DEFAULT 0 COMMENT '本次巡检发现的待检测提交数量',
  MODIFY COLUMN error_message VARCHAR(2000) NULL COMMENT '巡检失败信息',
  MODIFY COLUMN started_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '巡检开始时间',
  MODIFY COLUMN finished_at DATETIME(3) NULL COMMENT '巡检完成时间';

ALTER TABLE analysis_task COMMENT = '变更影响分析任务表';
ALTER TABLE analysis_task
  MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '分析任务主键ID（UUID）',
  MODIFY COLUMN project_id CHAR(36) NOT NULL COMMENT '关联服务ID',
  MODIFY COLUMN base_commit VARCHAR(64) NOT NULL COMMENT '分析起始提交SHA',
  MODIFY COLUMN target_commit VARCHAR(64) NOT NULL COMMENT '分析目标提交SHA',
  MODIFY COLUMN status VARCHAR(30) NOT NULL COMMENT '任务状态：READY/RUNNING/SUCCESS/FAILED/NO_CHANGES',
  MODIFY COLUMN commit_count INT NOT NULL DEFAULT 0 COMMENT '间隔提交数量',
  MODIFY COLUMN changed_file_count INT NOT NULL DEFAULT 0 COMMENT '变更文件数量',
  MODIFY COLUMN additions INT NOT NULL DEFAULT 0 COMMENT '新增代码行数',
  MODIFY COLUMN deletions INT NOT NULL DEFAULT 0 COMMENT '删除代码行数',
  MODIFY COLUMN commit_summary JSON NULL COMMENT '提交摘要列表（JSON）',
  MODIFY COLUMN error_message VARCHAR(2000) NULL COMMENT '分析失败信息',
  MODIFY COLUMN risk_level VARCHAR(20) NULL COMMENT '规则分析风险等级',
  MODIFY COLUMN risk_summary VARCHAR(1000) NULL COMMENT '规则分析风险摘要',
  MODIFY COLUMN impacted_modules JSON NULL COMMENT '规则分析影响模块列表（JSON）',
  MODIFY COLUMN regression_suggestions JSON NULL COMMENT '规则分析回归建议列表（JSON）',
  MODIFY COLUMN symbol_summary VARCHAR(1000) NULL COMMENT 'TypeScript Symbol分析摘要',
  MODIFY COLUMN symbol_changes JSON NULL COMMENT 'TypeScript Symbol变更列表（JSON）',
  MODIFY COLUMN symbol_impacts JSON NULL COMMENT 'TypeScript Symbol调用影响列表（JSON）',
  MODIFY COLUMN change_evidence JSON NULL COMMENT '变更证据与调用链信息（JSON）',
  MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '任务创建时间',
  MODIFY COLUMN finished_at DATETIME(3) NULL COMMENT '任务完成时间';

ALTER TABLE change_file COMMENT = '分析任务变更文件明细表';
ALTER TABLE change_file
  MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '变更文件主键ID（UUID）',
  MODIFY COLUMN analysis_task_id CHAR(36) NOT NULL COMMENT '关联分析任务ID',
  MODIFY COLUMN file_path VARCHAR(1000) NOT NULL COMMENT '变更后的文件路径',
  MODIFY COLUMN old_path VARCHAR(1000) NULL COMMENT '重命名前的文件路径',
  MODIFY COLUMN change_type VARCHAR(10) NOT NULL COMMENT '变更类型：A新增/M修改/D删除/R重命名/C复制/T类型变化/U未合并',
  MODIFY COLUMN additions INT NOT NULL DEFAULT 0 COMMENT '文件新增行数',
  MODIFY COLUMN deletions INT NOT NULL DEFAULT 0 COMMENT '文件删除行数',
  MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';

ALTER TABLE ai_provider_config COMMENT = 'AI服务商配置表';
ALTER TABLE ai_provider_config
  MODIFY COLUMN id CHAR(36) NOT NULL COMMENT 'AI配置主键ID（UUID）',
  MODIFY COLUMN name VARCHAR(100) NOT NULL COMMENT 'AI配置名称',
  MODIFY COLUMN base_url VARCHAR(500) NOT NULL COMMENT 'AI接口基础地址',
  MODIFY COLUMN api_key_encrypted TEXT NOT NULL COMMENT '加密后的API Key',
  MODIFY COLUMN api_key_hint VARCHAR(20) NOT NULL COMMENT 'API Key脱敏展示尾段',
  MODIFY COLUMN model VARCHAR(150) NOT NULL COMMENT '模型名称',
  MODIFY COLUMN api_format VARCHAR(20) NOT NULL DEFAULT 'OPENAI' COMMENT '接口协议格式：OPENAI/ANTHROPIC',
  MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：0否/1是',
  MODIFY COLUMN is_default TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否为默认配置：0否/1是',
  MODIFY COLUMN timeout_ms INT NOT NULL DEFAULT 30000 COMMENT 'AI请求超时时间（毫秒）',
  MODIFY COLUMN max_files INT NOT NULL DEFAULT 80 COMMENT '单个AI分析批次最大文件数量',
  MODIFY COLUMN max_symbols INT NOT NULL DEFAULT 50 COMMENT '单个AI分析批次最大Symbol数量',
  MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
    ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

ALTER TABLE pending_notification_config COMMENT = '待检测通知全局配置表';
ALTER TABLE pending_notification_config
  MODIFY COLUMN id TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '全局通知配置固定主键',
  MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用待检测通知：0否/1是',
  MODIFY COLUMN webhook_encrypted TEXT NULL COMMENT '加密后的钉钉机器人Webhook',
  MODIFY COLUMN webhook_hint VARCHAR(32) NULL COMMENT 'Webhook脱敏展示尾段',
  MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
    ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

ALTER TABLE pending_notification_delivery COMMENT = '待检测通知成功投递记录表';
ALTER TABLE pending_notification_delivery
  MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '通知投递记录主键ID（UUID）',
  MODIFY COLUMN project_id CHAR(36) NOT NULL COMMENT '关联服务ID',
  MODIFY COLUMN target_commit VARCHAR(64) NOT NULL COMMENT '已通知的目标提交SHA',
  MODIFY COLUMN delivered_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '通知成功投递时间';
